### ISSUE TITLE
Segment Limits per Project

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#2] opened 2022-01-18 18:46 UTC
### Summary: 
Satellites have the ability to limit users on storage and bandwidth, we want to add the ability to limit segments as well. 

### Pain Point:
Users are uploading millions of very small objects (less than 5MB) creating millions of segments that the satellites must store metadata for. The metadata cost for these objects is more expensive than the cost to store the data which makes it difficult to operate a satellite without taking a loss.

### Intended Outcome:
Satellites will have the ability to set Segment limits on a per-project basis. There will be two limits, a limit for free accounts and a limit for paid accounts. This will give satellite operators flexibility to limit the number of segments a user can upload thus helping them control their metadata costs. 

### How will it work?
Satellite Operators will be able to set a per-project segment limit in the satellite config. 

### Links:
Milestone: https://github.com/storj/storj/milestone/3

**Comment by jtolio** [comment] 2022-02-23 21:30
Note from OKR tracking spreadsheet:
> Mostly completed from Metainfo team perspective, but there are 2 outstanding items required from sales and user growth.  Will follow up separately.

**Comment by shaupt131** [comment] 2022-03-03 14:50
Week 9 update:
- Feature is completed, functional, and deployed. 2 outstanding tasks remain:

- Default segment limits are currently applied, but new segment limits have been identified and are being implemented https://github.com/storj/storj/issues/4590

- UI bug discovered that we are working to get into an upcoming sprint https://github.com/storj/storj/issues/4388

**Comment by shaupt131** [comment] 2022-03-15 13:24
## Week 11 update:

- Updated segment limits have been merged, just waiting on deployment.
  - Once deployed, feature flag can be enabled.
- UI bug that hides certain upload error messages remains (https://github.com/storj/storj/issues/4388), but feature can still be used as intended.

**Comment by iglesiasbrandon** [comment] 2022-05-27 18:40
We initially deployed this functionality to all Storj DCS satellites in Q1 of 2022. We decided to roll back this change after we found a query that was overloading CRDB. We have since made improvements to resolve that issue (https://github.com/storj/storj/issues/4744) and it will be rolled back into production in the next release. Because of this, we are going to move this item to Q2.

**Closed** 2022-07-06 20:15 UTC
Labels: Satellite, Team-Metainfo
